# Generated by Django 6.0.2 on 2026-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VSaverSync',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(blank=True, max_length=60, null=True)),
                ('exregnodate', models.CharField(blank=True, max_length=30, null=True)),
                ('super_code', models.CharField(blank=True, max_length=5, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vsaver_sync',
                'ordering': ['code'],
            },
        ),
    ]
