# Generated by Django 5.0.2 on 2026-02-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccInvMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.BigIntegerField()),
                ('invdate', models.DateField(blank=True, null=True)),
                ('customerid', models.CharField(blank=True, max_length=30, null=True)),
                ('nettotal', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_invmast_sync',
                'ordering': ['-invdate', '-slno'],
                'unique_together': {('slno', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='AccMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(blank=True, max_length=60, null=True)),
                ('exregnodate', models.CharField(blank=True, max_length=30, null=True)),
                ('super_code', models.CharField(blank=True, max_length=5, null=True)),
                ('phone2', models.CharField(blank=True, max_length=60, null=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_master_sync',
                'ordering': ['code'],
                'unique_together': {('code', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='Misel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'misel_sync',
                'unique_together': {('firm_name', 'client_id')},
            },
        ),
        migrations.DeleteModel(
            name='VSaverSync',
        ),
    ]
