# Generated by Django 6.0.2 on 2026-02-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accinvmast_accmaster_misel_delete_vsaversync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccInvMast',
        ),
        migrations.RemoveField(
            model_name='accmaster',
            name='phone2',
        ),
    ]
