# Generated by Django 5.0.2 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accinvmast_accmaster_misel_delete_vsaversync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accinvmast',
            name='client_id',
            field=models.CharField(db_index=True, default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accmaster',
            name='client_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='misel',
            name='client_id',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
