# Generated by Django 6.0.2 on 2026-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_accinvmast_remove_accmaster_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccInvMast',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invdate', models.DateField(blank=True, null=True)),
                ('customerid', models.CharField(blank=True, max_length=30, null=True)),
                ('nettotal', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_invmast_sync',
                'ordering': ['-invdate', '-slno'],
            },
        ),
    ]
