# Generated by Django 6.0.2 on 2026-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accinvmast'),
    ]

    operations = [
        migrations.AddField(
            model_name='accmaster',
            name='phone2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
