# Generated by Django 6.0.2 on 2026-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accmaster_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='accinvmast',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accmaster',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='misel',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
